### ISSUE TITLE
Package subpath './transformer' is not defined by "exports"

### ISSUE THREAD

**Issue by mryechkin** [probablyup/twyx#1]
Hey! This looks really interesting :)

I wanted to try it out, but am getting this error at runtime. Tried in both Next.js and Vite, same error in both instances.

<img width="983" alt="Screenshot 2023-09-20 at 6 59 58 PM" src="https://github.com/probablyup/twyx/assets/5657181/1838149d-dcc1-4ee4-bd9a-37ca4055be53">

<img width="899" alt="Screenshot 2023-09-20 at 7 22 25 PM" src="https://github.com/probablyup/twyx/assets/5657181/1f6dbdb5-c0fd-4399-a4fd-f514632e75c5">

What's really strange is I can see the package in `node_modules` with the correct `exports` field in `package.json` 😕 

Any ideas what might be causing this?

Here's a reproduction repo for reference - it's just a brand new Vite + React app: https://github.com/mryechkin/twyx-app-repro

**Comment by probablyup** [comment]
That is weird :( I will experiment tonight and see if I can find a culprit. Thanks for letting me know

**Comment by mryechkin** [comment]
Awesome. Sounds good! Thank you for replying so quickly. I am very intrigued to try this out

**Comment by probablyup** [comment]
Should be working now with 0.1.2! I needed to add one thing to your `tailwind.config.js`:

```diff
content: {
  transform: {
    js: transformTwyxProps,
+   jsx: transformTwyxProps,
    tsx: transformTwyxProps,
  }
}
```

Since the `jsx` file type is in use, it has to be individually specified

**Comment by mryechkin** [comment]
I also tried importing directly from `.generated` path, but then get a different error about `ast-types` missing:

```js
import { transformTwyxProps } from "twyx/.generated/transformer";
```

![Screenshot 2023-09-21 at 10 15 54 AM](https://github.com/probablyup/twyx/assets/5657181/276f5ca2-254f-40a8-9106-d08fe08ff9e4)

**Comment by probablyup** [comment]
So weird... it's set up the same way twyx/react is https://github.com/probablyup/twyx/blob/f7bcd9807db5371269e101ae0e5322a5fbe09ae8/package.json#L16

I'll keep digging

**Comment by mryechkin** [comment]
Yeah.. super weird! And I see you have a working Codesandbox example as well now, which makes it even more confusing as to why. Everything looks to be setup the same way. Could this be a Vite specific thing?

**Comment by probablyup** [comment]
Ok I _think_ this fixes it: https://github.com/probablyup/twyx/commit/4a5d22f4f890b4dc9c4a808b604fffa89b64903a

It's been really weird to debug... it seems like vite doesn't ingest the `module` package.json key in the same way as other tools

**Comment by probablyup** [comment]
Just working on getting the release script to work through changesets

**Comment by probablyup** [comment]
Done https://github.com/probablyup/twyx/releases/tag/v0.1.4 :) 

Tested in your repo and I think it's working now!

**Comment by mryechkin** [comment]
Confirmed - working now! 🎉  Thank you so much!
